# GitHub Sponsors, OpenCollective, or other funding links
# See https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

# Uncomment and set your funding links below:
# github: [your-github-username]
# open_collective: your-opencollective
# patreon: your-patreon
ko_fi: aliraxa
# custom: ['https://your-custom-funding-link.com']
